[build-system]
requires = [
    "setuptools >= 61.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "lambdapdk"
authors = [{name = "Zero ASIC"}]
description = "Library of open source Process Design Kits"
readme = "README.md"
urls = {Homepage = "https://github.com/siliconcompiler/lambdapdk"}
requires-python = ">= 3.8"
license = {file = "LICENSE"}
dependencies = [
    "siliconcompiler >= 0.17.0"
]
version = "0.1.0"

[tool.pytest.ini_options]
testpaths = "tests"
timeout = "180"

[project.optional-dependencies]
# Dev dependencies.
dev = [
    "flake8>=5.0.0",
    "pytest",
    "tclint"
]

[tool.tclint]
exclude = [
    'build',
    'scripts/build',
    'dist'
]

[tool.tclint.style]
line-length = 100
